# imagen limpia que se quiere usar
FROM openjdk:17-jdk-alpine
# comando que copia la app dentro de la imagen
COPY target/webcliente-1.jar webcliente-1.jar
# ejecutará dentro de la imagen la app
ENTRYPOINT ["java","-jar","/webcliente-1.jar"]
# expone el puerto
EXPOSE 8088